---
title: "Gender Name Bias (N=750)"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: 
    toc: yes
    toc_depth: 2
    fig_caption: true
header-includes:
  \renewcommand{\contentsname}{Items}
   \usepackage{fvextra}
   \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	results = "hide"
)
library(dplyr)
library(lmtest)
library(sandwich)
library(systemfit)
library(car)
library(broom)
library(qualtRics)
library(knitr)
library(rmarkdown)
library(ggplot2)
library(grid)
library(extrafont)
library(readxl)
library(nnet)
library(systemfit)
library(aod)
library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r include=FALSE}
if ( (!is.null(knitr::current_input()))) {
  if (("pdf_document" ==
                rmarkdown::all_output_formats(knitr::current_input())[1])) {
      stargazer_type <- "latex"
  }
} else {
  stargazer_type <- "text"
}

robust_summary <- function(model) {
    # Calculating robust standard errors
    robust_se <- sqrt(diag(vcovHC(model, type = "HC3")))

    # Getting original model summary
    model_summary <- summary(model)

    # Updating standard errors, t-values, and p-values in the coefficients table
    model_summary$coefficients[, "Std. Error"] <- robust_se
    model_summary$coefficients[, "t value"] <- model_summary$coefficients[, "Estimate"] / robust_se
    model_summary$coefficients[, "Pr(>|t|)"] <- 2 * pt(-abs(model_summary$coefficients[, "t value"]), df = model_summary$df[2], lower.tail = TRUE)

    return(model_summary)
}
robust_confint <- function(model, level = 0.95) {
    # Calculating robust standard errors
    robust_se <- sqrt(diag(vcovHC(model, type = "HC3")))

    # Getting the coefficients
    est <- coef(model)

    # Calculating the critical value for the t-distribution
    alpha <- 1 - level
    t_crit <- qt(1 - alpha / 2, df = df.residual(model))

    # Calculating the confidence intervals
    lower <- est - t_crit * robust_se
    upper <- est + t_crit * robust_se

    # Combining into a matrix
    confint <- cbind(lower, upper)
    rownames(confint) <- names(est)
    colnames(confint) <- c("2.5 %", "97.5 %")

    return(confint)
}

```

\newpage

## Read Data

```{r echo=TRUE}
#write.csv(qual_data, "raw_data.csv")
## Pull directly from Qualtrics API
qual_data <- fetch_survey(surveyID='SV_8whRwyQHrL0PdD8',
                   label = T,
                   convert = F,
                   start_date = "2024-11-22",
                   force_request = T)

# Read the Excel file
professors_data <- read_excel("Nameselect_1022_humancheck.xlsx")
```